"""empty message

Revision ID: 540281b653a9
Revises: 5725ac6db950
Create Date: 2021-12-27 16:24:48.450786

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '540281b653a9'
down_revision = '5725ac6db950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'given')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('given', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
