"""empty message

Revision ID: ad96c87adca6
Revises: 3dcddc5723b9
Create Date: 2021-12-13 01:40:03.941808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad96c87adca6'
down_revision = '3dcddc5723b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'admin')
    # ### end Alembic commands ###
